server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: domain
  datasource:
    url: jdbc:mysql://localhost:3308/anime?createDatabaseIfNotExist=true
    username: root
    password: teste
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2 Essentials By DevDojo
  github: https://github.com/xGuiilherme/domain